"""
Expensify Integration Server HTTP client.

The Expensify API uses a two-step export flow:

  Step 1 — POST with type "file" + Freemarker CSV template
            Response: plain-text filename, e.g. "exportXXX.csv"

  Step 2 — POST with type "download" + filename (no template)
            Response: raw CSV bytes generated by the template

fetch_all_csvs() fires all three template calls (reports, transactions,
actions) sequentially and returns raw bytes for each.  No JSON parsing
is performed anywhere in this module.
"""

from __future__ import annotations

import time
from pathlib import Path
from typing import Any
import json

import requests

from scripts.config import AppConfig
from scripts.logger import get_logger
from scripts.rate_limiter import RateLimiter
from scripts.retry import retryable_request

log = get_logger(__name__)

# How long to wait between download-poll attempts (seconds)
_POLL_INTERVAL = 4.0
# Maximum number of poll attempts before giving up
_POLL_MAX_ATTEMPTS = 15

# Sentinel responses that mean "file not generated yet — retry"
_NOT_READY_SENTINELS = frozenset({"null", "", "undefined"})


class ExpensifyAPIError(Exception):
    """Raised when the API returns an unexpected or unrecoverable response."""


# ---------------------------------------------------------------------------
# Client
# ---------------------------------------------------------------------------


class ExpensifyClient:
    """HTTP client for the Expensify Integration Server.

    Downloads expense data as raw CSV files generated server-side by
    Freemarker templates.  No JSON parsing is performed.

    Args:
        config:       Loaded application configuration.
        rate_limiter: Rate limiter instance shared across all calls.
    """

    def __init__(self, config: AppConfig, rate_limiter: RateLimiter) -> None:
        self._config = config
        self._rate_limiter = rate_limiter
        self._session = self._build_session()
        self._reports_template = self._load_template(config.reports_template_path)
        self._transactions_template = self._load_template(config.transactions_template_path)
        self._actions_template = self._load_template(config.actions_template_path)

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def fetch_all_csvs(self, start_date: str, end_date: str) -> dict[str, bytes]:
        """Fetch all three CSV files for the given date range.

        Makes three sequential API calls — one per Freemarker template —
        and returns raw CSV bytes for each.

        An empty period (no reports) yields header-only bytes for each key.
        Callers should check the transaction count before saving files.

        Args:
            start_date: ISO-8601 date string, e.g. ``"2026-01-01"``.
            end_date:   ISO-8601 date string, e.g. ``"2026-01-31"``.

        Returns:
            Dict with keys ``"reports"``, ``"transactions"``, ``"actions"``
            mapping to raw CSV bytes.

        Raises:
            ExpensifyAPIError: On API-level errors or exhausted poll attempts.
            requests.HTTPError: On unrecoverable HTTP errors after all retries.
        """
        log.info("Fetching all CSVs: start=%s end=%s", start_date, end_date)
        t_start = time.perf_counter()

        result = {
            "reports": self._fetch_one_csv(
                self._reports_template, start_date, end_date, label="reports"
            ),
            "transactions": self._fetch_one_csv(
                self._transactions_template, start_date, end_date, label="transactions"
            ),
            "actions": self._fetch_one_csv(
                self._actions_template, start_date, end_date, label="actions"
            ),
        }

        elapsed = time.perf_counter() - t_start
        log.info(
            "All CSVs fetched: start=%s end=%s elapsed=%.2fs "
            "reports=%d bytes transactions=%d bytes actions=%d bytes",
            start_date,
            end_date,
            elapsed,
            len(result["reports"]),
            len(result["transactions"]),
            len(result["actions"]),
        )
        return result

    def close(self) -> None:
        """Release the underlying HTTP session."""
        self._session.close()

    def __enter__(self) -> "ExpensifyClient":
        return self

    def __exit__(self, *_: Any) -> None:
        self.close()

    # ------------------------------------------------------------------
    # Single-template CSV fetch
    # ------------------------------------------------------------------

    def _fetch_one_csv(
        self, template: str, start_date: str, end_date: str, label: str = ""
    ) -> bytes:
        """Run the two-step export flow for one template and return raw bytes."""
        log.info("Requesting export: label=%s start=%s end=%s", label, start_date, end_date)
        filename = self._request_export(template, start_date, end_date)
        log.info("Export queued: label=%s filename=%s", label, filename)
        content = self._poll_download(filename, label=label)
        log.info("Download complete: label=%s bytes=%d", label, len(content))
        return content

    # ------------------------------------------------------------------
    # Step 1: request export
    # ------------------------------------------------------------------

    def _request_export(self, template: str, start_date: str, end_date: str) -> str:
        """POST the file-export job; return the filename from the response."""
        response = self._post_file(template=template, start_date=start_date, end_date=end_date)
        filename = response.text.strip()

        if not filename or not filename.startswith("export"):
            log.error(
                "Unexpected response from file step: %r (status=%d)",
                filename[:200],
                response.status_code,
            )
            raise ExpensifyAPIError(
                f"Expected an export filename but got: {filename!r}"
            )

        return filename

    @retryable_request
    def _post_file(self, template: str, start_date: str, end_date: str) -> requests.Response:
        """Send the Step-1 multipart request and return the raw Response."""
        self._rate_limiter.acquire()

        job_description = json.dumps({
            "type": "file",
            "credentials": {
                "partnerUserID": self._config.partner_user_id,
                "partnerUserSecret": self._config.partner_user_secret,
            },
            "onReceive": {
                "immediateResponse": ["returnRandomFileName"],
            },
            "inputSettings": {
                "type": "combinedReportData",
                "filters": {
                    "startDate": start_date,
                    "endDate": end_date,
                },
            },
            "outputSettings": {
                "fileExtension": "csv",
            },
        })

        log.debug("Step 1 POST start=%s end=%s", start_date, end_date)

        response = self._session.post(
            url=self._config.api_url,
            data={
                "requestJobDescription": job_description,
                "template": template,
            },
            timeout=self._config.timeout,
        )

        self._check_http_errors(response, step="file")
        return response

    # ------------------------------------------------------------------
    # Step 2: poll + download
    # ------------------------------------------------------------------

    def _poll_download(self, filename: str, label: str = "") -> bytes:
        """Poll the download endpoint until the file is ready.

        Expensify processes exports asynchronously.  The sentinel "null"
        (4 bytes) means the file is not yet generated — we sleep and retry.

        Any other response (including a header-only CSV for an empty period)
        is treated as a valid completed response and returned as-is.

        Args:
            filename: The export filename returned by Step 1.
            label:    Human-readable label for log messages.

        Returns:
            Raw CSV bytes.

        Raises:
            ExpensifyAPIError: After exhausting all poll attempts.
        """
        for attempt in range(1, _POLL_MAX_ATTEMPTS + 1):
            try:
                response = self._post_download(filename=filename)
                content = response.content
                text = content.decode("utf-8", errors="replace").strip()

                if text in _NOT_READY_SENTINELS:
                    raise ExpensifyAPIError(
                        f"File not ready yet — server returned: {text!r}"
                    )

                return content

            except ExpensifyAPIError as exc:
                if attempt >= _POLL_MAX_ATTEMPTS:
                    log.error(
                        "Download failed after %d attempts for %s (%s): %s",
                        _POLL_MAX_ATTEMPTS,
                        filename,
                        label,
                        exc,
                    )
                    raise

                log.info(
                    "File not ready (attempt %d/%d) [%s]: %s — retrying in %.1fs …",
                    attempt,
                    _POLL_MAX_ATTEMPTS,
                    label,
                    exc,
                    _POLL_INTERVAL,
                )
                time.sleep(_POLL_INTERVAL)

        raise ExpensifyAPIError(
            f"Exhausted {_POLL_MAX_ATTEMPTS} download attempts for {filename}"
        )

    @retryable_request
    def _post_download(self, filename: str) -> requests.Response:
        """Send the Step-2 download request and return the raw Response."""
        self._rate_limiter.acquire()

        job_description = json.dumps({
            "type": "download",
            "credentials": {
                "partnerUserID": self._config.partner_user_id,
                "partnerUserSecret": self._config.partner_user_secret,
            },
            "fileName": filename,
        })

        log.debug("Step 2 POST filename=%s", filename)

        response = self._session.post(
            url=self._config.api_url,
            data={"requestJobDescription": job_description},
            timeout=self._config.timeout,
            stream=True,
        )

        self._check_http_errors(response, step="download")
        return response

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _build_session(self) -> requests.Session:
        session = requests.Session()
        adapter = requests.adapters.HTTPAdapter(
            pool_connections=2,
            pool_maxsize=4,
            max_retries=0,
        )
        session.mount("https://", adapter)
        session.mount("http://", adapter)
        return session

    @staticmethod
    def _load_template(path: Path) -> str:
        log.debug("Loading Freemarker template from %s", path)
        return path.read_text(encoding="utf-8")

    @staticmethod
    def _check_http_errors(response: requests.Response, step: str) -> None:
        if response.status_code == 429:
            log.warning("HTTP 429 from Expensify API (step=%s).", step)
            response.raise_for_status()
        if response.status_code >= 500:
            log.warning(
                "HTTP %d from Expensify API (step=%s) — will retry.",
                response.status_code, step,
            )
            response.raise_for_status()
        if not response.ok:
            log.error("HTTP %d from Expensify API (step=%s).", response.status_code, step)
            response.raise_for_status()
